# Generated by Django 4.2.1 on 2023-08-12 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hod", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Teacher",
            new_name="Leaders",
        ),
    ]
