# Generated by Django 4.2.1 on 2023-09-04 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("hod", "0005_category_delete_leaders_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "my_date_field",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="department",
            old_name="Classes",
            new_name="Class_name",
        ),
        migrations.RenameField(
            model_name="department",
            old_name="Department",
            new_name="Department_name",
        ),
    ]
