# Generated by Django 4.2.1 on 2023-09-04 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hod", "0006_mymodel_rename_classes_department_class_name_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MyModel",
        ),
        migrations.RenameField(
            model_name="department",
            old_name="Class_name",
            new_name="Classes",
        ),
        migrations.RenameField(
            model_name="department",
            old_name="Department_name",
            new_name="Department",
        ),
    ]
