# Generated by Django 4.2.1 on 2023-09-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hod", "0007_delete_mymodel_rename_class_name_department_classes_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="Department_name",
            new_name="Divisions",
        ),
        migrations.RemoveField(
            model_name="course",
            name="dpt",
        ),
        migrations.AddField(
            model_name="course",
            name="No_of_students",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="No_of_teachers",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
