# Generated by Django 4.2.1 on 2023-09-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hod", "0008_rename_department_name_course_divisions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="Divisions",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="No_of_students",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="No_of_teachers",
            field=models.IntegerField(null=True),
        ),
    ]
