# Generated by Django 4.2.1 on 2023-09-06 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hod", "0009_alter_course_divisions_alter_course_no_of_students_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("student", models.CharField(max_length=200, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Present", "Present"), ("Absent", "Absent")],
                        max_length=10,
                    ),
                ),
                (
                    "st",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hod.student"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="block",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="dpt",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="room",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="student",
        ),
        migrations.RemoveField(
            model_name="deallocation_request",
            name="block",
        ),
        migrations.RemoveField(
            model_name="deallocation_request",
            name="dpt",
        ),
        migrations.RemoveField(
            model_name="deallocation_request",
            name="room",
        ),
        migrations.RemoveField(
            model_name="deallocation_request",
            name="student",
        ),
        migrations.RemoveField(
            model_name="mess_track",
            name="block",
        ),
        migrations.RemoveField(
            model_name="mess_track",
            name="dpt",
        ),
        migrations.RemoveField(
            model_name="mess_track",
            name="student",
        ),
        migrations.RemoveField(
            model_name="messcomplaint",
            name="block",
        ),
        migrations.RemoveField(
            model_name="messcomplaint",
            name="student",
        ),
        migrations.RemoveField(
            model_name="room",
            name="block",
        ),
        migrations.RemoveField(
            model_name="room",
            name="room",
        ),
        migrations.RemoveField(
            model_name="room_rent",
            name="block",
        ),
        migrations.RemoveField(
            model_name="room_rent",
            name="dpt",
        ),
        migrations.RemoveField(
            model_name="room_rent",
            name="room",
        ),
        migrations.RemoveField(
            model_name="room_rent",
            name="student",
        ),
        migrations.DeleteModel(
            name="Block",
        ),
        migrations.DeleteModel(
            name="Complaint",
        ),
        migrations.DeleteModel(
            name="Deallocation_Request",
        ),
        migrations.DeleteModel(
            name="Mess_track",
        ),
        migrations.DeleteModel(
            name="MessComplaint",
        ),
        migrations.DeleteModel(
            name="Room",
        ),
        migrations.DeleteModel(
            name="Room_rent",
        ),
    ]
