# Generated by Django 4.2.1 on 2023-09-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hod", "0010_attendance_remove_complaint_block_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="No_of_teachers",
        ),
        migrations.AddField(
            model_name="course",
            name="Teachers",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
