# Generated by Django 4.2.1 on 2023-09-14 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hod", "0012_remove_course_divisions_remove_course_no_of_students_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="Class",
            new_name="Classes",
        ),
    ]
