# Generated by Django 4.2.1 on 2023-09-14 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hod", "0015_alter_student_classes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance",
            old_name="student",
            new_name="Course_name",
        ),
        migrations.RenameField(
            model_name="attendance",
            old_name="date",
            new_name="Date",
        ),
        migrations.AddField(
            model_name="attendance",
            name="Division",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="Month",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="Student_name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="cs",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="hod.course"
            ),
            preserve_default=False,
        ),
    ]
