# Generated by Django 4.2.1 on 2023-09-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hod", "0017_delete_admission_fee_delete_category_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance",
            old_name="attended",
            new_name="Attendance",
        ),
        migrations.RenameField(
            model_name="attendance",
            old_name="date",
            new_name="Date",
        ),
        migrations.AddField(
            model_name="attendance",
            name="Classes",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="Division",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="Student_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
